#ifndef CHARDEV_IOCTL
#define CHARDEV_IOCTL

#define CHARDEV_IOC_MAGIC 'x'

#define CHARDEV_IOCTL_CLEAR _IO(CHARDEV_IO_MAGIC, 0)
#define CHARDEV_IOCTL_GETLEN _IOR(CHARDEV_IO_MAGIC, 1, int)

#endif // CHARDEV_IOCTL