#ifndef USER_TEST_H
#define USER_TEST_H

#include <sys/ioctl.h>

#define CHARDEV_IO_MAGIC 'x'

#define CHARDEV_IOCTL_CLEAR _IO(CHARDEV_IO_MAGIC, 0)
#define CHARDEV_IOCTL_GETLEN _IOR(CHARDEV_IO_MAGIC, 1, int)
#define CHARDEV_IOCTL_SETLEN _IOW(CHARDEV_IO_MAGIC, 2, int)

#endif // USER_TEST_H